# Generated by Django 4.1.2 on 2022-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
